Repository EasyCrypt/easycrypt, pull requests merged in 2022-10, with the labels that each got.

#239 Add conditional probability distributions
  theories/distributions/Distr.ec
Labels: enhancement, library

#272 Add postfix notations.
  examples/UC/RndO.ec
  src/ecLexer.mll
  src/ecParser.mly
  src/ecPrinting.ml
  theories/core/CoreReal.ec
  theories/datatypes/Real.ec
Labels: enhancement

#273 Fix pretty-printing of high-order postfix operators
  src/ecPrinting.ml
Labels: bug, enhancement

#285 lossless for equiv
  src/phl/ecPhlHiAuto.ml
Labels: enhancement

#289 Fix a bug when replaying a removed user reduction rule
  src/ecTheoryReplay.ml
Labels: bug

#288 add missing restriction in the case of adversary
  examples/upto_syntaxtic.ec
  src/phl/ecPhlUpto.ml
Labels: bug

#235 port Dexcepted to dresrict and deprecate Dfilter
  theories/distributions/Dexcepted.ec
  theories/distributions/Dfilter.ec
  theories/distributions/Distr.ec
Labels: enhancement

#293 Register for the pretty-printer
  src/ec.ml
  src/ecCorePrinting.ml
  src/ecPrinting.mli
Labels: enhancement

#301 telescoping_sum + sum p^i + sum i*p^i
  theories/algebra/Bigalg.ec
  theories/algebra/Ring.ec
  theories/algebra/StdBigop.ec
Labels: enhancement
