Repository EasyCrypt/easycrypt, pull requests merged in 2022-09, with the labels that each got.

#226 [breaking] fix unsoundness in pHL while rule
  examples/PIR.ec
  examples/PRG.ec
  examples/vonNeumann.eca
  src/phl/ecPhlWhile.ml
  theories/distributions/Dexcepted.ec
Labels: breaking change

#258 [stdlib]: Matrix: coeffs in a comm. ring instead of an ID.
  theories/algebra/Matrix.eca
Labels: library

#262 [while (phl, >=)]: be more restrictive on the variant delta lower-bound
  src/ecPV.mli
  src/phl/ecPhlWhile.ml
Labels: bug

#266 [conv]: add case for program variables
  src/ecReduction.ml
Labels: blocking
