Repository EasyCrypt/easycrypt, pull requests merged in 2022-03, with the labels that each got.

#151 stronger version of dmap1E_can
  theories/distributions/Distr.ec
Labels: enhancement, library

#152 Add lemma divzmul_divdiv and strenghten/proof modz_pow2_div.
  theories/algebra/IntDiv.ec
Labels: enhancement, library

#164 [tactic]: [rewrite]: support for multi-rules
  src/ecHiGoal.ml
Labels: enhancement

#168 [tactic]: [proc*]: fix procedure's arguments substitution
  dune-project
  src/phl/ecPhlFun.ml
Labels: bug, enhancement
