Repository EasyCrypt/easycrypt, pull requests merged in 2022-12, with the labels that each got.

#312 Various bug fixes for clones (modules & lemmas)
  src/ecCorePrinting.ml
  src/ecEnv.mli
  src/ecHiGoal.ml
  src/ecMatching.ml
  src/ecParsetree.ml
  src/ecReduction.ml
  src/ecThCloning.ml
  src/ecTheoryReplay.ml
Labels: bug

#254 Deploy oldlibs cleanup
  examples/Pedersen.ec
  examples/SchnorrPK.ec
  examples/UC/MapAux.ec
  examples/UC/dh_enc_cost.ec
  examples/cramer-shoup/cramer_shoup.ec
  examples/elgamal.ec
  examples/hashed_elgamal_generic.ec
  examples/hashed_elgamal_std.ec
  examples/old/list-ddh/DDH.ec
  examples/old/list-ddh/DDH_indexed.ec
  examples/old/list-ddh/RandOracle.ec
  examples/old/list-ddh/list_ddh.ec
  examples/old/list-ddh/list_ddh_no_inner.ec
  examples/old/trapdoor.ec
  examples/to-port/PSS.ec
  examples/to-port/hashed_elgamal.ec
  theories/algebra/Group.ec
  theories/algebra/ZModP.ec
  theories/crypto/DLog.ec
  theories/crypto/DiffieHellman.ec
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/assumptions/ODH.ec
  theories/dune
  theories/encryption/DDH_hybrid.ec
  theories/oldlibs/CyclicGroup.ec
  theories/oldlibs/Cyclic_group_prime.ec
  theories/oldlibs/OldDistrCheck.ec
  theories/oldlibs/PrimeField.ec
  theories/oldlibs/Prime_field.ec
Labels: enhancement, library

#313 [tactic]: fix t_solve performance issues
  src/ecLowGoal.ml
  src/ecLowGoal.mli
Labels: enhancement
