Repository EasyCrypt/easycrypt, pull requests merged in 2023-09, with the labels that each got.

#430 Operators body can now be formulas
  src/ecCoreFol.ml
  src/ecCoreFol.mli
  src/ecDecl.ml
  src/ecDecl.mli
  src/ecEnv.ml
  src/ecFol.ml
  src/ecHiGoal.ml
  src/ecInductive.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/ecReduction.ml
  src/ecScope.ml
  src/ecSection.ml
  src/ecSmt.ml
  src/ecSubst.ml
  src/ecThCloning.ml
  src/ecThCloning.mli
  src/ecTheoryReplay.ml
  src/ecUserMessages.ml
  theories/algebra/Ideal.ec
Labels: enhancement

#433 hint simplify now extracts rewriting rules from <=>
  src/ecReduction.ml
Labels: enhancement

#434 [runtest]: new CLI argument --bin
  Makefile
  config/tests.config
  scripts/testing/runtest
  src/ec.ml
Labels: enhancement

#431 Operator unfolding when applied to enough arguments
  src/ecCallbyValue.ml
  src/ecDecl.ml
  src/ecDecl.mli
  src/ecEnv.ml
  src/ecEnv.mli
  src/ecHiGoal.ml
  src/ecLowGoal.ml
  src/ecLowGoal.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecReduction.ml
  src/ecReduction.mli
  src/ecScope.ml
  src/ecSection.ml
  src/ecSubst.ml
  src/ecTheoryReplay.ml
  src/phl/ecPhlConseq.ml
  src/phl/ecPhlSkip.ml
Labels: enhancement

#436 [nix] vendor prover derivations
  default.nix
  scripts/nix/LICENSE
  scripts/nix/alt-ergo/default.nix
  scripts/nix/cvc4/cvc4-bash-patsub-replacement.patch
  scripts/nix/cvc4/default.nix
  scripts/nix/cvc4/minisat-fenv.patch
  scripts/nix/cvc5/default.nix
  scripts/nix/z3/default.nix
Labels: enhancement

#438 cloning: fix regression bug in operators convertibilty check
  src/ecTheoryReplay.ml
Labels: bug

#447 stdlib: limit of the inverse of a sequence
  theories/algebra/Ring.ec
  theories/analysis/RealSeq.ec
Labels: library

#448 remove hyp in normrV
  theories/algebra/Number.ec
Labels: library

#449 add more lemmas on `convergeto`
  theories/analysis/RealSeq.ec
Labels: library

#445 Read idirs from the ECPATH environment variable
  src/ecOptions.ml
Labels: enhancement

#450 add lemma on summable
  theories/analysis/RealSeries.ec
  theories/structure/Discrete.ec
Labels: library

#452 op: fix creation of refined operators
  src/ecScope.ml
Labels: bug

#453 In subst, when crossing a binding, remove the bound variable.
  src/ecCoreFol.ml
Labels: bug

#456 Internal: do not consider an applied abstract module as a non-functor…
  src/ecPath.ml
Labels: bug

#435 opsem: generate spec lemmas
  src/ecProcSem.ml
  src/ecScope.ml
Labels: enhancement
