Repository EasyCrypt/easycrypt, pull requests merged in 2023-02, with the labels that each got.

#337 Implement a naive termination checker
  src/ecHiInductive.ml
  src/ecTypes.ml
  src/ecTypes.mli
  src/ecTyping.ml
  src/ecTyping.mli
  src/ecUserMessages.ml
  theories/datatypes/List.ec
Labels: bug, enhancement

#336 Fix encoding of Why3 fixpoint containing higher-order calls to itself
  src/ecSmt.ml
Labels: bug

#339 default.nix: option to install provers
  default.nix
Labels: enhancement

#341 [theories]: lemmas for dcond and dbiased
  theories/distributions/DBool.ec
  theories/distributions/Distr.ec
Labels: enhancement, library

#342 [theories]: finite expectation (`Jensen_fin_concave`)
  theories/distributions/Distr.ec
Labels: enhancement, library

#343 [theories]: port "lock" from MathComp
  theories/prelude/Logic.ec
Labels: enhancement, library

#344 [theories]: add various individual lemmas
  theories/algebra/Bigalg.ec
  theories/analysis/RealSeries.ec
  theories/datatypes/Int.ec
  theories/datatypes/List.ec
  theories/distributions/DBool.ec
  theories/distributions/SDist.ec
  theories/structure/Finite.ec
Labels: enhancement, library
