Repository EasyCrypt/easycrypt, pull requests merged in 2023-12, with the labels that each got.

#476 Allows selecting a prover by its version number.
  Makefile
  src/ec.ml
  src/ecProvers.ml
  src/ecProvers.mli
Labels: enhancement

#475 Why3 1.7 as a minimal version
  README.md
  default.nix
  dune-project
  easycrypt.opam
  scripts/docker/Makefile
  scripts/docker/build-box/Dockerfile
  scripts/docker/build-box/alt-ergo
  scripts/nix/alt-ergo/default.nix
Labels: enhancement, breaking change

#484 In substitutions, lazyly refresh the codomain of the univar map
  src/ecTypes.ml
Labels: bug

#485 Reduced rndsem
  src/ecHiTacticals.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlRnd.ml
  src/phl/ecPhlRnd.mli
Labels: enhancement, tactics

#488 Add tactic `weakmem`
  src/ecHiTacticals.ml
  src/ecLexer.mll
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlCodeTx.ml
  src/phl/ecPhlCodeTx.mli
  theories/distributions/Dexcepted.ec
Labels: tactics

#489 CI: skip duplicated jobs
  .github/workflows/ci.yml
Labels: enhancement

#473 [tactic] outline
  src/ecCoreModules.ml
  src/ecCoreModules.mli
  src/ecHiTacticals.ml
  src/ecLexer.mll
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecUnifyProc.ml
  src/ecUnifyProc.mli
  src/phl/ecPhlOutline.ml
  src/phl/ecPhlOutline.mli
  tests/outline.ec
Labels: enhancement, tactics
