Repository EasyCrypt/easycrypt, pull requests merged in 2023-06, with the labels that each got.

#387 [internal] Removed `smart` constructors for various internal constructions.
  src/ecCoreFol.ml
  src/ecCoreFol.mli
  src/ecCoreModules.ml
  src/ecEnv.ml
  src/ecMatching.ml
  src/ecPath.ml
  src/ecTypes.ml
Labels: enhancement

#388 [lib] FSet: fcard_eq1
  theories/datatypes/FSet.ec
Labels: enhancement, library

#159 Tighten the ROM bad call results
  theories/crypto/ROM.eca
Labels: enhancement

#392 Take PolyReduce theory from Kyber project
  theories/algebra/PolyReduce.ec
Labels: enhancement, library

#400 Prove Fermat's little theorem
  theories/algebra/Bigalg.ec
  theories/algebra/Group.ec
  theories/algebra/IntDiv.ec
  theories/algebra/StdBigop.ec
  theories/algebra/ZModP.ec
  theories/datatypes/List.ec
Labels: library

#407 proc op: add support for the "local" modifier
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecScope.ml
Labels: enhancement

#406 [chore] remove more raw smt calls
  theories/algebra/Bigop.eca
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/prp_prf/Strong_RP_RF.eca
Labels: library, chore
