Repository EasyCrypt/easycrypt, pull requests merged in 2024-10, with the labels that each got.

#635 stop normalizing lemmas/operators w.r.t. module aliases
  src/ecEnv.ml
  src/ecEnv.mli
Labels: enhancement

#628 CI: only for PR & main
  .github/workflows/ci.yml
Labels: chore

#605 split SmtMap into SMT Array and finite map
  examples/ChaChaPoly/chacha_poly.ec
  examples/ChaChaPoly/ske.ec
  examples/MEE-CBC/CBC.eca
  examples/PRG.ec
  examples/UC/MapAux.ec
  examples/UC/RndO.ec
  examples/br93.ec
  examples/prg-tutorial/PRF.eca
  examples/prg-tutorial/PRGc.ec
  theories/crypto/PRF.eca
  theories/crypto/PROM.ec
  theories/crypto/PRP.eca
  theories/crypto/ROM.eca
  theories/crypto/SplitRO.ec
  theories/crypto/assumptions/AEAD.ec
  theories/crypto/assumptions/CRHash.ec
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/assumptions/MRPKE.ec
  theories/crypto/assumptions/ODH.ec
  theories/crypto/assumptions/PKSMK.ec
  theories/crypto/prp_prf/Strong_RP_RF.eca
  theories/crypto/ske/NewSKE.eca
  theories/datatypes/FMap.ec
  theories/datatypes/SmtMap.ec
  theories/distributions/Mu_mem.ec
  theories/distributions/SDist.ec
  theories/modules/RndProd.eca
  theories/newth/SmtMap.ec
Labels: breaking change

#651 Fix set_set_swap statement and proof.
  theories/datatypes/Word.eca
Labels: bug

#648 `proc rewrite` now supports the `/=` rule
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlRewrite.ml
  src/phl/ecPhlRewrite.mli
  tests/procrewrite-simpl.ec
Labels: enhancement

#649 Propagate extended code positions to more tactics
  src/ecCorePrinting.ml
  src/ecHiTacticals.ml
  src/ecLowPhlGoal.ml
  src/ecMatching.ml
  src/ecMatching.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/ecProofTyping.ml
  src/ecProofTyping.mli
  src/ecTyping.ml
  src/ecTyping.mli
  src/ecUtils.ml
  src/ecUtils.mli
  src/phl/ecPhlApp.ml
  src/phl/ecPhlApp.mli
  src/phl/ecPhlCodeTx.ml
  src/phl/ecPhlCodeTx.mli
  src/phl/ecPhlEager.ml
  src/phl/ecPhlEager.mli
  src/phl/ecPhlEqobs.ml
  src/phl/ecPhlFel.ml
  src/phl/ecPhlFel.mli
  src/phl/ecPhlHiCond.ml
  src/phl/ecPhlInline.ml
  src/phl/ecPhlLoopTx.ml
  src/phl/ecPhlLoopTx.mli
  src/phl/ecPhlOutline.ml
  src/phl/ecPhlOutline.mli
  src/phl/ecPhlRCond.ml
  src/phl/ecPhlRCond.mli
  src/phl/ecPhlRewrite.ml
  src/phl/ecPhlRewrite.mli
  src/phl/ecPhlRnd.ml
  src/phl/ecPhlRnd.mli
  src/phl/ecPhlRwEquiv.ml
  src/phl/ecPhlRwEquiv.mli
  src/phl/ecPhlSp.ml
  src/phl/ecPhlSp.mli
  src/phl/ecPhlWp.ml
  src/phl/ecPhlWp.mli
  tests/codepos-assign-with-name.ec
Labels: enhancement

#650 The tactic `swap` now takes generalized code position.
  src/ecCorePrinting.ml
  src/ecHiTacticals.ml
  src/ecMatching.ml
  src/ecMatching.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/phl/ecPhlSwap.ml
  src/phl/ecPhlSwap.mli
  theories/distributions/DJoin.ec
Labels: enhancement, breaking change

#655 lexer: do not lex decimal numbers when the parser won't accept them
  src/ecIo.ml
Labels: bug, enhancement

#656 unroll for: constant-propagate the counter
  src/ecMatching.ml
  src/ecMatching.mli
  src/phl/ecPhlLoopTx.ml
  tests/cfold.ec
Labels: enhancement, breaking change

#657 fix "unroll for" failure (InvalidCPos)
  src/ecCorePrinting.ml
  src/ecMatching.ml
  src/ecMatching.mli
  src/ecPrinting.ml
  src/phl/ecPhlLoopTx.ml
Labels: bug

#658 Fix deep code positions parsing
  src/ecParser.mly
Labels: bug

#654 Improve code positions (match + extended assignments)
  src/ecMatching.ml
  src/ecMatching.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/ecTyping.ml
  src/phl/ecPhlInline.ml
  tests/match_codepos.ec
Labels: enhancement
