Repository EasyCrypt/easycrypt, pull requests merged in 2024-05, with the labels that each got.

#545 [subst]: fix name capture
  src/ecCoreSubst.ml
Labels: bug

#543 Change `axiom eq_choice` to lemma
  theories/prelude/Logic.ec
Labels: library

#547 [runtest] fix TTY detection
  scripts/testing/runtest
Labels: bug

#548 Remove non-strict proof mode.
  src/ecCommands.ml
  src/ecCommands.mli
  src/ecHiGoal.ml
  src/ecHiGoal.mli
  src/ecHiTacticals.ml
  src/ecLexer.mll
  src/ecLowGoal.ml
  src/ecLowGoal.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecScope.ml
  src/ecScope.mli
  theories/query_counting/OracleBounds.ec
Labels: breaking change

#552 Reduce equalities between record literals.
  src/ecReduction.ml
  tests/reduction-record-eqyality.ec
Labels: enhancement
