Repository EasyCrypt/easycrypt, pull requests merged in 2024-08, with the labels that each got.

#592 More results on lists (take/drop) and bit-encoding (bs2int/chunk)
  theories/datatypes/BitEncoding.ec
  theories/datatypes/List.ec
Labels: library

#599 Change default pp width from 20 to 80
  src/ecPrinting.ml
Labels: enhancement

#601 [External CI] Add XMSS and SPHINCS+
  .github/workflows/external.json
Labels: external ci
