Repository EasyCrypt/easycrypt, pull requests merged in 2024-09, with the labels that each got.

#606 external CI checks for PR-specific branch
  .github/workflows/ci.yml
Labels: chore, external ci

#581 Simple tactics in proof-terms.
  src/ecCoreGoal.ml
  src/ecCoreGoal.mli
  src/ecHiGoal.ml
  src/ecHiGoal.mli
  src/ecHiTacticals.ml
  src/ecLowGoal.ml
  src/ecLowGoal.mli
  src/ecMaps.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecProofTerm.ml
  src/ecScope.ml
  tests/done_in_proofterm.ec
Labels: enhancement

#608 [ci] diversified external CI selects a valid branch
  .github/workflows/ci.yml
Labels: chore, external ci

#607 stage the SmtMap -> FMap renaming
  theories/datatypes/FMap.ec
Labels: chore

#612 internal: stable ordering of globals components
  examples/ChaChaPoly/chacha_poly.ec
  examples/cramer-shoup/cramer_shoup.ec
  examples/plug-and-pray/Plug_and_Pray_example.ec
  src/ecCommands.ml
  src/ecEnv.ml
  src/ecEnv.mli
  theories/crypto/RndExcept.eca
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/assumptions/PKSMK.ec
  theories/encryption/Hybrid.ec
  theories/encryption/Indist.ec
Labels: chore, breaking change

#616 internals: user-defined rules can be headed by a projection
  src/ecCallbyValue.ml
  src/ecEnv.ml
  src/ecEnv.mli
  src/ecLowGoal.ml
  src/ecReduction.ml
  src/ecTheory.ml
  src/ecTheory.mli
Labels: enhancement

#618 cloning: do not allow realizing a non-axiomatic lemma
  src/ecThCloning.ml
  src/ecThCloning.mli
  src/ecTheoryReplay.ml
  src/ecUserMessages.ml
Labels: bug

#619 runtest: lint code + fix warnings
  scripts/testing/runtest
Labels: chore

#623 user reduction: fix some incompleteness issues
  src/ecCallbyValue.ml
  src/ecReduction.ml
Labels: bug

#627 ci: compile with warning as errors
  .github/workflows/ci.yml
  Makefile
  src/dune
Labels: enhancement, chore

#620 runtest: properly restore the terminal on (exceptional) exit
  scripts/testing/runtest
Labels: bug

#622 pretty-printer/parser: improve reparsability of the pretty-printer output
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/ecTyping.ml
Labels: enhancement, chore

#626 Fix logical variable shadowing program variables
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/ecTyping.ml
Labels: bug, enhancement

#624 pretty-printing: rework the pretty-printing of module restrictions
  src/ecPrinting.ml
Labels: bug, enhancement
