Repository EasyCrypt/easycrypt, pull requests merged in 2024-07, with the labels that each got.

#560 [pretty-printing]: pretty-print in the theory environment of the targ…
  src/ecEnv.ml
  src/ecEnv.mli
  src/ecPrinting.ml
  src/ecScope.ml
  src/ecSection.ml
  src/ecSection.mli
Labels: chore, technical-debt

#571 [internal]: fix filtering as saved theory-related environments
  src/ecEnv.ml
  src/ecPath.ml
  src/ecPath.mli
  src/ecTheoryReplay.ml
  src/ecTyping.ml
Labels: bug

#574 make dapply a parsing-only abbreviation
  theories/distributions/Distr.ec
Labels: technical-debt

#575 Remove the "nosmt" mechanism
  src/ecDecl.ml
  src/ecDecl.mli
  src/ecEnv.ml
  src/ecHiGoal.ml
  src/ecInductive.ml
  src/ecLexer.mll
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecPrinting.ml
  src/ecScope.ml
  src/ecSection.ml
  src/ecSmt.ml
  src/ecSubst.ml
  src/ecTheoryReplay.ml
  theories/algebra/Bigalg.ec
  theories/algebra/Bigop.eca
  theories/algebra/DynMatrix.eca
  theories/algebra/Group.ec
  theories/algebra/IntDiv.ec
  theories/algebra/Matrix.eca
  theories/algebra/Monoid.eca
  theories/algebra/Number.ec
  theories/algebra/Perms.ec
  theories/algebra/Ring.ec
  theories/algebra/StdBigop.ec
  theories/analysis/RealExp.ec
  theories/analysis/RealFun.ec
  theories/analysis/RealLub.ec
  theories/analysis/RealSeries.ec
  theories/core/Bool.ec
  theories/core/Core.ec
  theories/core/CoreInt.ec
  theories/crypto/PRP.eca
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/prp_prf/Strong_RP_RF.eca
  theories/datatypes/Array.ec
  theories/datatypes/BitEncoding.ec
  theories/datatypes/FSet.ec
  theories/datatypes/Int.ec
  theories/datatypes/IntMin.ec
  theories/datatypes/List.ec
  theories/datatypes/Real.ec
  theories/datatypes/Tuple.eca
  theories/datatypes/Word.eca
  theories/datatypes/Xreal.ec
  theories/distributions/Dexcepted.ec
  theories/distributions/Dfilter.ec
  theories/distributions/Distr.ec
  theories/newth/SmtMap.ec
  theories/prelude/Logic.ec
  theories/prelude/Tactics.ec
  theories/structure/Discrete.ec
  theories/structure/Subtype.eca
  theories/structure/WF.ec
  theories/tactics/AlgTactic.ec
Labels: breaking change, technical-debt

#577 Fixing bug in elim* when a bound is given.
  src/ecCoreFol.ml
  src/ecCoreFol.mli
  src/ecFol.ml
  src/ecFol.mli
  src/ecPrinting.ml
  src/phl/ecPhlExists.ml
Labels: bug

#579 [stdlib]: List: more lemmas on insert and related
  theories/datatypes/List.ec
Labels: library

#580 [stdlib]: remove axioms (int + inductive schemes)
  src/ecEnv.ml
  src/ecScope.ml
  theories/datatypes/Int.ec
  theories/datatypes/List.ec
Labels: library

#584 Fully check external project that compiles in <10 minutes.
  .github/workflows/external.json
Labels: external ci

#583 [stdlib]: extra lemmas on dprod.
  theories/distributions/Distr.ec
Labels: library

#582 [stdlib]: more lemmas on distributions over lists
  theories/distributions/DList.ec
Labels: library

#586 [smt]: proper selection of SMT variant
  examples/ChaChaPoly/chacha_poly.ec
  src/ec.ml
  src/ecProvers.ml
  src/ecProvers.mli
  theories/distributions/DInterval.ec
Labels: breaking change
