Repository EasyCrypt/easycrypt, pull requests merged in 2024-01, with the labels that each got.

#493 Refactoring & simplfication of the low-level substitution.
  src/ecAst.ml
  src/ecAst.mli
  src/ecCallbyValue.ml
  src/ecCoreFol.ml
  src/ecCoreFol.mli
  src/ecCoreModules.ml
  src/ecCoreModules.mli
  src/ecCoreSubst.ml
  src/ecCoreSubst.mli
  src/ecDecl.ml
  src/ecEnv.ml
  src/ecEnv.mli
  src/ecFol.ml
  src/ecFol.mli
  src/ecHiGoal.ml
  src/ecHiInductive.ml
  src/ecHiNotations.ml
  src/ecHiPredicates.ml
  src/ecLowGoal.ml
  src/ecMatching.ml
  src/ecPrinting.ml
  src/ecProofTerm.ml
  src/ecProofTyping.ml
  src/ecReduction.ml
  src/ecScope.ml
  src/ecSection.ml
  src/ecSmt.ml
  src/ecTheoryReplay.ml
  src/ecTypes.ml
  src/ecTypes.mli
  src/ecTyping.ml
  src/ecUnify.ml
  src/ecUserMessages.ml
  src/phl/ecPhlCond.ml
  src/phl/ecPhlOutline.ml
  src/phl/ecPhlRCond.ml
Labels: enhancement

#516 Update tactic: rewrite equiv
  examples/ChaChaPoly/chacha_poly.ec
  examples/Dice4_6.ec
  examples/MEE-CBC/CBC.eca
  examples/rwequiv.ec
  src/ecHiGoal.ml
  src/ecHiTacticals.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlOutline.mli
  src/phl/ecPhlRwEquiv.ml
  src/phl/ecPhlRwEquiv.mli
  tests/rwequiv.ec
  theories/crypto/PROM.ec
  theories/crypto/PRP.eca
  theories/crypto/ROM.eca
  theories/crypto/SplitRO.ec
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/prp_prf/Strong_RP_RF.eca
  theories/distributions/DList.ec
  theories/distributions/SDist.ec
  theories/looping/FoldProc.eca
  theories/looping/IterProc.eca
  theories/modules/RndProd.eca
Labels: tactics

#500 New tactic: "proc case"
  src/ecHiTacticals.ml
  src/ecPV.ml
  src/ecPV.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlCodeTx.ml
  src/phl/ecPhlCodeTx.mli
  tests/asgncase.ec
Labels: tactics

#458 Remove module overriding
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecThCloning.ml
  src/ecThCloning.mli
  src/ecUserMessages.ml
Labels: bug, breaking change
