Repository EasyCrypt/easycrypt, pull requests merged in 2024-04, with the labels that each got.

#528 runtest: fix regexp escapes + deprecation warnings
  scripts/testing/runtest
Labels: bug

#491 New tactic: "proc change"
  src/ecHiTacticals.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlRewrite.ml
  src/phl/ecPhlRewrite.mli
  tests/procchange.ec
Labels: enhancement, tactics

#531 runtest: accept all options from the prover/loader group
  .github/workflows/ci.yml
  Makefile
  scripts/testing/runtest
  src/ec.ml
  src/ecOptions.ml
  src/ecOptions.mli
Labels: enhancement

#492 New tactic: "proc rewrite"
  src/ecHiTacticals.ml
  src/ecLowGoal.ml
  src/ecMatching.ml
  src/ecMatching.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/phl/ecPhlRewrite.ml
  src/phl/ecPhlRewrite.mli
  tests/procrewrite.ec
Labels: tactics

#530 Allow patterns in cut-rewrite.
  src/ecHiGoal.ml
  src/ecParser.mly
  tests/rw_explicit_eq_with_pattern.ec
Labels: enhancement

#532 stdlib: bigop: split sums between even- and odd- indices
  theories/algebra/Bigop.eca
Labels: library

#535 [ci] do not use set-output anymore
  .github/workflows/ci.yml
Labels: chore

#536 [ci] add ML-KEM
  .github/workflows/external.json
Labels: chore

#538 [ci] separate status for all external projects
  .github/workflows/ci.yml
Labels: chore

#539 External CI: add cryptobox
  .github/workflows/external.json
Labels: external ci

#510 tactic: match: out of TCB
  src/ecCoreGoal.ml
  src/ecCoreGoal.mli
  src/ecLowGoal.ml
  src/ecLowGoal.mli
  src/ecLowPhlGoal.ml
  src/phl/ecPhlCodeTx.ml
  src/phl/ecPhlCond.ml
  src/phl/ecPhlCond.mli
  src/phl/ecPhlExists.mli
  src/phl/ecPhlHiCond.ml
  src/phl/ecPhlLoopTx.ml
  src/phl/ecPhlRewrite.ml
Labels: enhancement, tactics

#542 [ci] dump & upload errors
  .github/workflows/ci.yml
  src/ec.ml
  src/ecOptions.ml
  src/ecOptions.mli
Labels: external ci

#540 [external ci] add xsalsa security
  .github/workflows/external.json
Labels: external ci
