Repository EasyCrypt/easycrypt, pull requests merged in 2025-01, with the labels that each got.

#675 Tactic `split` with break position
  src/ecCoreLib.ml
  src/ecCoreLib.mli
  src/ecFol.ml
  src/ecHiGoal.ml
  src/ecHiGoal.mli
  src/ecHiTacticals.ml
  src/ecLowGoal.ml
  src/ecLowGoal.mli
  src/ecMatching.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecProofTerm.ml
  src/ecProofTerm.mli
  tests/split.ec
  theories/prelude/Tactics.ec
Labels: enhancement

#681 get rid of `axiomatized by` in favor of `[opaque]` with trivial lemma
  examples/MEE-CBC/FunctionalSpec.ec
  theories/algebra/Group.ec
  theories/algebra/IntDiv.ec
  theories/crypto/assumptions/DHIES.ec
  theories/datatypes/Array.ec
  theories/datatypes/FMap.ec
  theories/datatypes/FSet.ec
  theories/datatypes/Word.eca
  theories/distributions/DList.ec
  theories/distributions/Distr.ec
  theories/prelude/Logic.ec
Labels: chore

#665 Better operators overloading inference
  src/ecHiInductive.ml
  src/ecPrinting.ml
  src/ecScope.ml
  src/ecTyping.ml
  src/ecUnify.ml
  src/ecUnify.mli
  tests/overloading.ec
Labels: enhancement

#661 Fine Grained Module Definitions
  examples/br93.ec
  src/ecLowPhlGoal.ml
  src/ecMatching.ml
  src/ecMatching.mli
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecTyping.ml
  src/ecTyping.mli
  src/ecUserMessages.ml
  tests/fine-grained-module-defs.ec
Labels: enhancement

#686 Service commit (docker / nix / dune)
  dune-project
  easycrypt.opam
  flake.lock
  flake.nix
  scripts/docker/Dockerfile.base
  scripts/docker/Dockerfile.build
Labels: chore

#687 Service commit (expain flag for menhir)
  dune-project
  src/dune
Labels: chore

#690 FMap: add lemmas on range after update
  theories/datatypes/FMap.ec
Labels: library

#674 Upgrade to why3 1.8
  dune-project
  easycrypt.opam
  src/ecCoq.ml
  src/ecProvers.ml
Labels: chore

#693 [external CI] use dev branch for XSalsa checks
  .github/workflows/external.json
Labels: external ci

#692 Improve transitivity* and replace*
  examples/ChaChaPoly/chacha_poly.ec
  src/phl/ecPhlOutline.ml
  src/phl/ecPhlOutline.mli
  src/phl/ecPhlRwEquiv.ml
  src/phl/ecPhlTrans.ml
  src/phl/ecPhlTrans.mli
  theories/crypto/PROM.ec
Labels: enhancement, breaking change
