Repository EasyCrypt/easycrypt, pull requests merged in 2025-03, with the labels that each got.

#731 remove duplicated code from EcAst
  src/ecAst.ml
  src/ecAst.mli
Labels: chore

#736 CI: update image from ubuntu-20.04 to ubuntu-24.04
  .github/workflows/ci.yml
Labels: chore

#728 Improvements to module tweaks
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecTyping.ml
  tests/fine-grained-module-defs.ec
Labels: enhancement

#734 Hi-level error message when `subst` fails
  src/ecCorePrinting.ml
  src/ecHiGoal.ml
  src/ecLowGoal.ml
  src/ecLowGoal.mli
  src/ecPrinting.ml
Labels: bug

#743 Minor fixes for sim
  src/ecPV.ml
  src/phl/ecPhlEqobs.ml
Labels: enhancement, tactics

#748 Hi-level error message in clone (axiom <-)
  src/ecHiGoal.ml
Labels: bug, enhancement

#727 Reworked outline tactic
  examples/MEE-CBC/CBC.eca
  src/ecMatching.ml
  src/ecParser.mly
  src/ecParsetree.ml
  src/ecProofTyping.ml
  src/ecProofTyping.mli
  src/ecTyping.mli
  src/ecUnifyProc.ml
  src/ecUnifyProc.mli
  src/phl/ecPhlOutline.ml
  src/phl/ecPhlOutline.mli
  tests/outline.ec
  theories/crypto/PRP.eca
  theories/crypto/ROM.eca
  theories/crypto/SplitRO.ec
  theories/crypto/assumptions/DHIES.ec
  theories/crypto/prp_prf/Strong_RP_RF.eca
  theories/distributions/DList.ec
  theories/distributions/SDist.ec
  theories/looping/FoldProc.eca
  theories/looping/IterProc.eca
  theories/modules/RndProd.eca
Labels: enhancement, breaking change, tactics

#757 stdlib: in Field, do not erase the unit predicate
  theories/algebra/Ring.ec
Labels: bug

#754 fix tactic ehoare-if
  src/phl/ecPhlCond.ml
Labels: bug, breaking change
